name: Windows CI Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Qt
      - name: Install Qt
        id: install-qt # Даем id этому шагу, чтобы получить путь
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.2'
          arch: 'win64_msvc2019_64'
          cached: 'true'

      # 3. Настраиваем окружение MSVC (ВАЖНЫЙ ШАГ)
      - name: Setup MSVC environment
        uses: microsoft/setup-msvc@v2
        with:
          # Можно указать конкретную версию, но по умолчанию он выберет последнюю подходящую
          # vs-version: 'latest'

      # 4. Собираем проект
      - name: Build with qmake and jom
        shell: bash # Используем bash для более удобной работы с переменными окружения
        run: |
          # Добавляем путь к jom.exe в PATH
          export PATH="${{ steps.install-qt.outputs.qtPath }}/bin:$PATH"
          
          # Запускаем сборку
          qmake DubbingTool.pro -spec win32-msvc "CONFIG+=release"
          jom -j$(nproc)
          
      # 5. Собираем все необходимые DLL
      - name: Deploy Qt dependencies
        run: |
          windeployqt.exe --release --no-translations --no-opengl-sw --no-svg --no-network --no-xml release/DubbingTool.exe
          
      # 6. Подготавливаем артефакт
      - name: Prepare artifact
        shell: bash
        run: |
          mkdir artifact
          mv release/* artifact/

      # 7. Загружаем артефакт
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DubbingTool-Windows-x64
          path: artifact
          retention-days: 90