name: Ultimate Sanity Check

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show directory content
        run: dir

      - name: Success
        run: echo "The most basic action 'actions/checkout' was resolved and worked!"
